language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "0.12"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"
  - "5.1"
  - "5.2"
  - "5.3"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
