language: node_js
node_js:
  - "6.12"
  - "7.10"
  - "8.9"
  - "9.3"
sudo: false
env:
  - CC=gcc-6 CXX=g++-6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
